version: '3.8'

services:
  royal-banners-api:
    build: .
    # 🔥 СЕНЬОРСКИЙ ХАК: Меняем имя образа, чтобы Portainer не смог использовать старый кэш и собрал всё заново!
    image: royal-banners-api:v2 
    container_name: royal-banners-api
    restart: always
    environment:
      - PORT=5005
      - NODE_ENV=production
      - DATABASE_URL=postgresql://yeee:Qazplm01@datebase:5432/royal_banners?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "5005:5005"
    networks:
      - shared_db_network

networks:
  shared_db_network:
    external: true
    name: universal_db_network